/* INVOICES */
export const GET_CUSTOMER_CONFIGURATIONS = "GET_CUSTOMER_CONFIGURATIONS"
export const GET_CUSTOMER_CONFIGURATIONS_SUCCESS = "GET_CUSTOMER_CONFIGURATIONS_SUCCESS"
export const GET_CUSTOMER_CONFIGURATIONS_FAIL = "GET_CUSTOMER_CONFIGURATIONS_FAIL"

export const GET_CUSTOMER_CONFIGURATION_DETAIL = "GET_CUSTOMER_CONFIGURATION_DETAIL"
export const GET_CUSTOMER_CONFIGURATION_DETAIL_SUCCESS = "GET_CUSTOMER_CONFIGURATION_DETAIL_SUCCESS"
export const GET_CUSTOMER_CONFIGURATION_DETAIL_FAIL = "GET_CUSTOMER_CONFIGURATION_DETAIL_FAIL"
